name: using the composite action

runs:
  using: "composite"
  steps:
    - name: Installing the java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: setup the python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

  
