name: using the composite action

inputs:
 java-version:
   required: true
   default: '21'
 distribution:
   required: true 
   default: 'temurin'
 python-version:
   required: true 
   default: '3.13'
outputs:
 repo-owner: 
   value: ${{ steps.vars.outputs.repo_owner }}
 branch:
   value: ${{ steps.vars.outputs.default_branch }}
   

runs:
  using: "composite"
  steps:
    - name: Installing the java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        

    - name: setup the python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: variables 
      id: vars
      run: |
        echo "repo_owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "default_branch=main" >> $GITHUB_OUTPUT


  
