name: manual workflow 

on:
  workflow_dispatch: 
   inputs:
     name: 
       description: "This simple name"
       type: string 
       required: true 
       default: "STR"
     gender:
       description: "Enter your gender"
       type: choice
       required: true 
       options:
         - Male
         - Female
       
   
jobs:
  dummy-manual:
    runs-on: ubuntu-latest
    steps:
    - name: using the manual workflow
      run: "echo This is testing job" 

    - name: Display the input value 
      run: "echo ${{ inputs.name }}"

    - name: Display the gender value 
      run: "echo ${{ inputs.gender }}"  
